Remove Rider package, fails with trunk version [13:23:51.235 INF] Compiler 	severity: Error 	message: Library\PackageCache\com.unity.ide.rider@2.0.5\Rider\Editor\RiderScriptEditor.cs(411,14): error CS0618: 'AssetDatabaseExperimental.IsAssetImportWorkerProcess()' is obsolete: 'AssetDatabaseExperimental.IsAssetImportWork [13:23:51.242 INF] erProcess() has been deprecated. Use AssetDatabase.IsAssetImportWorkerProcess()'