Run performance tests only in 2019.2 or higher. For some reason it's not working in 2019.1 due errors
[08:51:06.906 INF] AssemblyCompilationErrors
	assembly: Library/ScriptAssemblies/Unity.PerformanceTesting.Editor.dll
	errors:
		C:/build/output/Unity-Technologies/com.unity.mobile.logcat/TestProjects/SampleProject2019.1Net35/Library/PackageCache/com.unity.test-framework.p
[08:51:06.910 INF] erformance@0.1.50-preview/Editor/EditmodeMetadataCollector.cs(13,13): error CS0012: The type `System.Object' is defined in an assembly that is not referenced. Consider adding a reference to assembly `netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

[08:51:08.120 INF] C:/build/output/Unity-Technologies/com.unity.mobile.logcat/TestProjects/SampleProject2019.1Net35/Library/PackageCache/com.unity.test-framework.performance@0.1.50-preview/Editor/EditmodeMetadataCollector.cs(13,13): error CS0012: The type `System.Object' is
[08:51:08.127 INF] defined in an assembly that is not referenced. Consider adding a reference to assembly `netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

[08:51:08.983 INF] Assembly 'Library/ScriptAssemblies/Unity.Mobile.AndroidLogcat.EditorTests.dll' will not be loaded due to errors:
Reference has errors 'Unity.PerformanceTesting'.
	C:\buildslave\unity\build\Runtime/Mono/MonoManager.cpp:1147

[08:51:08.988 INF] Assembly 'Library/ScriptAssemblies/Unity.PerformanceTesting.dll' will not be loaded due to errors:
Unable to resolve reference 'netstandard'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.
	C:\buildslave\unity\build\Runtime/Mono/MonoManager.cpp:1147